### ISSUE TITLE
issue with visual grasp

### ISSUE THREAD

**Issue by tianhaowuhz** [hwjiang1510/GraspTTA#5]
I am trying to visual the diverse grasp. However, the visualized policy seems wrong for some reason, I just follow the README, have no idea why this happen. I would be appreciate if some can help!
![image](https://user-images.githubusercontent.com/43113029/163750339-11800950-f991-4f06-a5e0-2a47668b51e9.png)

**Comment by hwjiang1510** [comment]
Please check if the PCA of MANO model is wrong (should be use_pca=True)

**Comment by tianhaowuhz** [comment]
> Please check if the PCA of MANO model is wrong (should be use_pca=True)
I do set use_pca=True, I found the issue is because "num_pca_comps", I set it to 51, then it shows correctly.

**Comment by xclucas** [comment]
> the issue is because "num_pca_comps"

Thank you for figuring this out! This fix is critical for getting the visualization to work. @hwjiang1510 please consider updating the code to prevent future users from confusion. Thanks
